"""changed link

Revision ID: bf1a8e5b1755
Revises: 55c23546b916
Create Date: 2024-03-05 17:55:45.392848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf1a8e5b1755'
down_revision: Union[str, None] = '55c23546b916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link_domain')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_domain',
    sa.Column('link_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('domain_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['links.id'], name='link_domain_domain_id_fkey'),
    sa.ForeignKeyConstraint(['link_id'], ['domains.id'], name='link_domain_link_id_fkey')
    )
    # ### end Alembic commands ###
